"""Durable, append-only record of confirmed job applications.

`jobs.db` is disposable working state -- discovery, scoring, and tailoring
output can all be regenerated by rerunning the pipeline, so wiping it during
testing is normal and safe. A confirmed application is not derived data: it's
the only record that a real, irreversible action was taken against a real
employer. Deleting `applypilot.db` (a documented, routine step when resetting
for a clean test run) silently destroyed that record along with everything
else, because both lived in the same file.

This log is a separate file for exactly that reason: no reset of `jobs.db`
can reach it. Every confirmed "applied" result -- from the agent or from a
manual `--mark-applied` correction -- gets one JSON line appended here at the
moment it's known to be true, independent of whatever later happens to the
database.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from applypilot import config

LOG_PATH: Path = config.APP_DIR / "applications_log.jsonl"


def record_application(
    url: str,
    title: str | None,
    applied_at: str | None = None,
    source: str = "agent",
    task_id: str | None = None,
) -> None:
    """Append one confirmed application to the durable log.

    Never overwrites or deduplicates on write -- a job legitimately submitted
    more than once (a real duplicate application, not just a retried DB
    write) should show up as more than one entry here. Counting distinct
    jobs applied to is a read-time concern (see count_applications), not a
    write-time one.
    """
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "url": url,
        "title": title,
        "applied_at": applied_at or datetime.now(timezone.utc).isoformat(),
        "source": source,
        "task_id": task_id,
    }
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")


def read_applications() -> list[dict]:
    """Every logged application event, in file order.

    Skips lines that fail to parse instead of raising -- a torn write from a
    killed process shouldn't take down `applypilot status`, and a partial
    last line is the one failure mode an append-only log can actually have.
    """
    if not LOG_PATH.exists():
        return []
    entries = []
    with LOG_PATH.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return entries


def count_applications() -> int:
    """Distinct jobs applied to -- what 'Applied' should report.

    Deduplicates by URL so a job resubmitted after a bug (or corrected twice)
    still counts once. The raw event list from read_applications() keeps the
    full history, including duplicates, for anyone investigating why a count
    doesn't match expectations.
    """
    return len({e["url"] for e in read_applications() if e.get("url")})
